### ISSUE TITLE
Target class does not exist

### ISSUE THREAD

**Issue by michaelangeloio** [FriendsOfFlarum/socialprofile#15]
Hi all!

Hope you're having a great new year so far!

Still learning and new to php/laravel, so this may be a dumb question. Any idea what this output means? 

[Whoops! There was an error..html.zip](https://github.com/FriendsOfFlarum/socialprofile/files/5862637/Whoops.There.was.an.error.html.zip)

Flarum Info:

![Screen Shot 2021-01-24 at 11 24 55 AM](https://user-images.githubusercontent.com/55844504/105636537-d6356300-5e36-11eb-9e0c-cbff67b35b50.png)

My flarum is running on Ubuntu with a managed MySQL backend on digital ocean. 

Let me know! 

Thank you, 

Michael Angelo Rivera

**Comment by dsevillamartin** [comment]
That error (`Target class [FoF\SocialProfile\Listeners\AddAttributes] does not exist.`) cannot happen with the latest version of Social Profile.  

You also don't seem to have Social Profile enabled, so this error is not from this extension... I don't know where it's from though.

**Comment by michaelangeloio** [comment]
Hi @datitisev !

Thank you for the quick reply. I believe this screenshot was actually when I removed the extension from `composer.json. `

Requiring this package in the `composer.json` results in the HTML error I provided you.

**Comment by dsevillamartin** [comment]
What version of the extension do you have installed?

**Comment by Ralkage** [comment]
Hey there @michaelangrivera 👋 are you still having this issue by any chance? Are you on the latest and greatest version of this extension as well?

**Comment by Ralkage** [comment]
Hey @michaelangrivera, we haven't heard from you in a while :) we are going to go ahead and close this issue for now; please feel free to create a new one if this issue persists 👍
