### ISSUE TITLE
Large gaps in text

### ISSUE THREAD

**Issue by ghost** [FriendsOfFlarum/socialprofile#21]
**This plugin creates large white spaces between texts in HTML text.**

Hi why is in CSS this code:

```
.Pages-container {
    max-width: 820px;
    white-space: pre-wrap;
}
```

I fix it to this, and text is displayed normally

```
.Pages-container {
    max-width: 820px;
    white-space: normal !important;
}
```
I don't know if this is the right procedure, but so far it works for me.

**Comment by dsevillamartin** [comment]
Has nothing to do with this extension.
