### ISSUE TITLE
Wrong package name: fof/socialprofile > fof/social-profile

### ISSUE THREAD

**Issue by jaz-on** [FriendsOfFlarum/socialprofile#3]
All packages use a dash when the name is made up of several words except for Social Profile.

**Exemple:**
fof/auth-discord
fof/secure-https
fof/user-bio
...

**But for some unknown reason:**
fof/socialprofile

**Comment by dsevillamartin** [comment]
Hm, I think it's a bit late to change this now. I agree it should've been `social-profile`, but I'd rather not have users need to change package.
