### ISSUE TITLE
preview stuck on loading icon

### ISSUE THREAD

**Issue by unknowndevice** [FriendsOfFlarum/socialprofile#7]
```
fof/socialprofile 0.1.2
flarum version: Flarum 0.1.0-beta.12
```

if you add a link to your profile and press save without an icon being selected or the loading icons spinning then it will select the loading icon as the icon for that link

_if you press save now_
<img width="70" alt="Screenshot 2020-03-24 at 19 20 06" src="https://user-images.githubusercontent.com/4682853/77468756-f440ca00-6e05-11ea-8a8a-635d125f1680.png">

_it will look like this._
![I5QMYd2](https://user-images.githubusercontent.com/4682853/77468736-ea1ecb80-6e05-11ea-958f-13509e80b78a.png)

to fix this just remove the link, and re-add it. this time selecting an icon, or waiting for the loading icon to finish finding one.

**Comment by imorland** [comment]
Fixed #18
